-- CreateTable
CREATE TABLE "USUARIOS" (
    "EMAIL" TEXT NOT NULL,
    "NOME" TEXT NOT NULL,
    "SENHA" TEXT NOT NULL,

    CONSTRAINT "USUARIOS_pkey" PRIMARY KEY ("EMAIL")
);

-- CreateTable
CREATE TABLE "INGREDIENTES" (
    "ID" SERIAL NOT NULL,
    "NOME" TEXT NOT NULL,
    "PRECO_UNITARIO" DOUBLE PRECISION NOT NULL,
    "GRAMATURA_UNITARIA" INTEGER NOT NULL,

    CONSTRAINT "INGREDIENTES_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "RECEITAS" (
    "ID" SERIAL NOT NULL,
    "NOME" TEXT NOT NULL,
    "QNT_PADRAO" DOUBLE PRECISION NOT NULL,
    "ID_USUARIO" TEXT NOT NULL,

    CONSTRAINT "RECEITAS_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "INGREDIENTES_RECEITA" (
    "ID_IR" SERIAL NOT NULL,
    "ID_RECEITA" INTEGER NOT NULL,
    "ID_INGREDIENTE" INTEGER NOT NULL,
    "PROPORCAO_INGREDIENTE" DOUBLE PRECISION NOT NULL,

    CONSTRAINT "INGREDIENTES_RECEITA_pkey" PRIMARY KEY ("ID_IR")
);

-- CreateIndex
CREATE UNIQUE INDEX "USUARIOS_EMAIL_key" ON "USUARIOS"("EMAIL");

-- AddForeignKey
ALTER TABLE "RECEITAS" ADD CONSTRAINT "RECEITAS_ID_USUARIO_fkey" FOREIGN KEY ("ID_USUARIO") REFERENCES "USUARIOS"("EMAIL") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "INGREDIENTES_RECEITA" ADD CONSTRAINT "INGREDIENTES_RECEITA_ID_RECEITA_fkey" FOREIGN KEY ("ID_RECEITA") REFERENCES "RECEITAS"("ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "INGREDIENTES_RECEITA" ADD CONSTRAINT "INGREDIENTES_RECEITA_ID_INGREDIENTE_fkey" FOREIGN KEY ("ID_INGREDIENTE") REFERENCES "INGREDIENTES"("ID") ON DELETE RESTRICT ON UPDATE CASCADE;
